name: open-neo-ui

services:
  api-python:
    build:
      context: ./services/api-python
      dockerfile: Dockerfile
    container_name: open-neo-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - OPEN_NEO_WORKSPACE=/workspace
      - OPEN_NEO_VERSION=0.3.3-beta
      - OLLAMA_URL=http://host.docker.internal:11434
    volumes:
      - open-neo-workspace:/workspace
  ollama:
    image: ollama/ollama:latest
    container_name: open-neo-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  open-neo-workspace:
  ollama-data:
