services:
  open-neo-ui:
    build: .
    container_name: open-neo-ui
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PYTHON_BRIDGE_URL=http://python-bridge:8787
    depends_on:
      - python-bridge
    restart: unless-stopped
    shm_size: "256mb"
    volumes:
      - ./data:/app/data
      - ./src:/app/src

  python-bridge:
    build:
      context: .
      dockerfile: Dockerfile.py
    container_name: neo-python-bridge
    ports:
      - "8787:8787"
    env_file: .env
    restart: unless-stopped
